channels:
- conda-forge
dependencies:
- python=3.13.5
- pip<=25.1.1
- pip:
  - mlflow==3.6.0
  - cloudpickle==3.1.1
  - numpy==2.2.5
  - pandas==2.2.3
  - psutil==7.1.3
  - scikit-learn==1.6.1
  - scipy==1.15.3
name: mlflow-env
